# Generated by Django 2.0.2 on 2020-04-27 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='usermane',
            new_name='username',
        ),
    ]
